#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
---
#@ workflow_name = "Docker Build"
name:  #@ workflow_name

"on":
  pull_request:
    paths:
      - ".dockerignore"
      - ".dockleignore"
      - ".github/workflows/*dockerfile*.yml"
      - "**/Dockerfile*"
  #! For caching docker layers in default branch.
  push:
    branches:
      - "main"

jobs:
  hadolint:
    name: docker / hadolint
    steps:
      #! recrusively lint files named '*Dockerfile*' pattern
      #!https://github.com/reviewdog/action-hadolint/blob/985a0c74c649805d539d5fecc971e512f7f55410/script.sh#L34
      - name: hadolint
        uses: reviewdog/action-hadolint@v1.26
        with:
          fail_on_error: true
          hadolint_flags: --failure-threshold warning

  scan_image:
    name: docker / vulnerability scan

    services:
      #! docker private registry
      #@ registry_image = "registry:5000/" + data.values.env.image
      #@ registry_push = "localhost:5000/" + data.values.env.image
      registry:
        image: registry:2
        ports:
          - 5000:5000

    #@yaml/text-templated-strings
    steps:
      #! Build image
      -  #@ template.replace(data.values.steps.setup_buildx)
      -  #@ template.replace(data.values.steps.run_buildx)
      -  #@ template.replace(data.values.steps.move_cache)
      #! Security Check
      - name: Enable problem matcher
        run: echo "::add-matcher::.github/workflows/dockle-problem-matcher.json"
      - name: Run Dockle
        id: dockle
        uses: docker://goodwithtech/dockle:latest
        with:
          #! wrong 'localhost', it is container localhost.
          args: --exit-code 1 (@= registry_image @):latest
        env:
          #! use HTTP option:
          #! https://github.com/goodwithtech/dockle/blob/master/cmd/dockle/main.go#L40
          DOCKLE_INSECURE: true
          DOCKLE_NON_SSL: true
      - name: Run Trivy
        id: trivy
        #@ pass_status = "fromJson('[ \"success\", \"failure\" ]')"
        if: |
          ${{ always() && contains(
            (@= pass_status -@), steps.dockle.outcome
          ) }}
        uses: aquasecurity/trivy-action@0.1.0
        with:
          image-ref: (@= registry_image @):latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
        env:
          TRIVY_NON_SSL: true

#@ pattern = {"name": workflow_name}
#@overlay/match by=overlay.subset(pattern)
---
jobs:
  scan_image:
    steps:
      #@overlay/match by=overlay.subset({"id": "buildx"})
      - id: buildx
        #@overlay/match missing_ok=True
        with:
          #! without network=host, failed to connection refused
          driver-opts: network=host
      #@overlay/match by=overlay.subset({"id":"docker_build"})
      - with:
          #@overlay/replace
          push: true
        env:
          #@yaml/text-templated-strings
          BUILD_IMAGE: (@= registry_push @)
