#! Useful github actions schema

#@data/values-schema
---
#! Cache dependencies and build outputs to improve workflow execution time.
#!
#! https://github.com/actions/cache
cache:
  name: Caching
  id: cache
  uses: actions/cache@v2
  with:
    path: ""
    key: ${{ env.CACHE_PREFIX }}-${{ env.CACHE_NAME }}-${{ env.CACHE_UNIQUE }}
    restore-keys: |
      ${{ env.CACHE_PREFIX }}-${{ env.CACHE_NAME }}-
  env:
    CACHE_PREFIX: ${{ runner.os }}
    CACHE_NAME: caching
    CACHE_UNIQUE: ${{ hashFiles('**/Dockerfile') }}

#! Set up docker buildx
setup_docker_buildx:
  name: Set up Docker Buildx
  id: setup-docker-buildx
  uses: docker/setup-buildx-action@v1
  with:
    #! without network=host, failed to connection refused when use a registrty container.
    driver-opts: network=host

#! Run docker buildx
#!
#! It is recommended that you perform the following two actions beforehand:
#!   - setup-buildx
#!   - setup-qmenu
#!
#! https://github.com/marketplace/actions/build-and-push-docker-images
docker_buildx:
  name: Docker Buildx
  id: docker-buildx
  uses: docker/build-push-action@v2
  with:
    push: false
    context: "."
    platforms: |
      linux/amd64
      linux/arm64
    tags: |
      ${{ env.BUILDX_IMAGE }}:latest
      ${{ env.BUILDX_IMAGE }}:v1
    cache-from: |
      type=local,src=${{ env.BUILDX_CACHE_FROM }}
    cache-to: |
      type=local,dest=${{ env.BUILDX_CACHE_TO }}
  env:
    BUILDX_IMAGE: ${{ github.repository }}
    BUILDX_CACHE_FROM: ""
    BUILDX_CACHE_TO: ""

#! HadoLint to the dockerfile by reviewdog
#!
#! reviewdog/action-hadolint recrusively lint files named '*Dockerfile*' pattern:
#!https://github.com/reviewdog/action-hadolint/blob/985a0c74c649805d539d5fecc971e512f7f55410/script.sh#L34
#!
#! https://github.com/hadolint/hadolint
#! https://github.com/reviewdog/action-hadolint
hadolint:
  name: hadolint
  uses: reviewdog/action-hadolint@v1.26
  with:
    fail_on_error: true
    hadolint_flags: --failure-threshold warning

dockle:
  name: Run Dockle
  id: dockle
  uses: docker://goodwithtech/dockle:latest
  with:
    args: --exit-code 1 ${{ env.DOCKER_IMAGE }}
  env:
    DOCKER_IMAGE: ""
    #! use HTTP option:
    #! https://github.com/goodwithtech/dockle/blob/master/cmd/dockle/main.go#L40
    DOCKLE_INSECURE: true
    DOCKLE_NON_SSL: true

trivy:
  name: Run Trivy
  id: trivy
  uses: aquasecurity/trivy-action@0.1.0
  with:
    image-ref: ${{ env.DOCKER_IMAGE }}
    format: table
    exit-code: 1
    ignore-unfixed: true
    vuln-type: os,library
    severity: CRITICAL,HIGH
  env:
    DOCKER_IMAGE: ""
    TRIVY_NON_SSL: true

upload_artifact:
  name: Upload artifact
  uses: actions/upload-artifact@v2
  with:
    name: my_artifact
    path: /tmp/my_artifact.tar
    retention-days: 7

download_artifact:
  name: Download artifact
  uses: actions/download-artifact@v2
  with:
    name: my_artifact
    path: /tmp
