name: Lint yaml
"on":
  pull_request:
    paths:
    - '**.ya?ml'
jobs:
  yamllint:
    name: yaml / lint
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2
    - name: yamllint
      uses: reviewdog/action-yamllint@v1.4
      with:
        fail_on_error: true
    runs-on: ubuntu-20.04
