name: Docker Build
"on":
  pull_request:
    paths:
    - .dockerignore
    - .dockleignore
    - .github/workflows/*dockerfile*.yml
    - '**/Dockerfile*'
  push:
    branches:
    - main
jobs:
  hadolint:
    name: docker / hadolint
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2
    - name: hadolint
      uses: reviewdog/action-hadolint@v1.26
      with:
        fail_on_error: true
        hadolint_flags: --failure-threshold warning
    runs-on: ubuntu-20.04
  build:
    name: docker / build
    services:
      registry:
        image: registry:2
        ports:
        - 5000:5000
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: setup-docker-buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - name: Cache Docker layers
      id: cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-build-rust-dockerfile-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-build-rust-dockerfile-
      env:
        CACHE_PREFIX: ${{ runner.os }}
        CACHE_NAME: caching
        CACHE_UNIQUE: ${{ hashFiles('**/Dockerfile') }}
    - name: Docker Buildx
      id: docker-buildx
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: |
          linux/amd64
          linux/arm64
        tags: |
          ${{ env.BUILDX_IMAGE }}:latest
          ${{ env.BUILDX_IMAGE }}:v1
        cache-from: |
          type=local,src=${{ env.BUILDX_CACHE_FROM }}
        cache-to: |
          type=local,dest=${{ env.BUILDX_CACHE_TO }}
      env:
        BUILDX_IMAGE: localhost:5000/${{ github.repository }}
        BUILDX_CACHE_FROM: /tmp/.buildx-cache
        BUILDX_CACHE_TO: /tmp/.buildx-cache-new
    - name: Replace the cache
      id: replace-cache
      run: |
        rm -rf ${CACHE_DEST}
        mv ${CACHE_SRC} ${CACHE_DEST}
      env:
        CACHE_SRC: /tmp/.buildx-cache-new
        CACHE_DEST: /tmp/.buildx-cache
    - name: Check images
      continue-on-error: true
      run: |
        echo "--- Registry ---"
        curl -Ss -X GET http://localhost:5000/v2/_catalog
        echo "--- Local ---"
        docker image ls
    - name: Save docker image
      run: |
        docker pull localhost:5000/${{ github.repository }}
        docker save \
          --output /tmp/my_built_image.tar \
          localhost:5000/${{ github.repository }}
    - name: Upload built image
      uses: actions/upload-artifact@v2
      with:
        name: my_built_image
        path: /tmp/my_built_image.tar
        retention-days: 7
    runs-on: ubuntu-20.04
  scan_image:
    name: docker / vulnerability scan
    needs: build
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: setup-docker-buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - name: Download built image
      uses: actions/download-artifact@v2
      with:
        name: my_built_image
        path: /tmp
    - name: Load image
      id: docker-load
      run: |
        docker load --input /tmp/my_built_image.tar
        docker image ls
    - name: Enable problem matcher
      run: echo "::add-matcher::.github/workflows/dockle-problem-matcher.json"
    - name: Run Dockle
      id: dockle
      uses: docker://goodwithtech/dockle:latest
      with:
        args: --exit-code 1 ${{ env.DOCKER_IMAGE }}
      env:
        DOCKER_IMAGE: localhost:5000/${{ github.repository }}:latest
        DOCKLE_INSECURE: true
        DOCKLE_NON_SSL: true
    - name: Run Trivy
      id: trivy
      uses: aquasecurity/trivy-action@0.1.0
      with:
        image-ref: ${{ env.DOCKER_IMAGE }}
        format: table
        exit-code: 1
        ignore-unfixed: true
        vuln-type: os,library
        severity: CRITICAL,HIGH
      env:
        DOCKER_IMAGE: localhost:5000/${{ github.repository }}:latest
        TRIVY_NON_SSL: true
    runs-on: ubuntu-20.04
  test:
    name: docker / compile test
    needs: build
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2
      with:
        repository: volta-cli/volta
        ref: v1.0.5
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: setup-docker-buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - name: Download built image
      uses: actions/download-artifact@v2
      with:
        name: my_built_image
        path: /tmp
    - name: Load image
      id: docker-load
      run: |
        docker load --input /tmp/my_built_image.tar
        docker image ls
    - name: Compile test
      run: |
        docker run --rm \
          --mount=type=bind,src="$(pwd)",dst=/project \
          localhost:5000/${{ github.repository }}
    - name: Validate static binary
      run: |
        file $PWD/target/release/volta
        ldd $PWD/target/release/volta

        if [ "$(objdump -p $PWD/target/release/volta | grep -c 'NEEDED')" -eq 0 ]; then
            echo "Static!"
        else
            echo "Dynamic!!!"
            exit 1
        fi
    - name: Check built exectable
      run: |
        $PWD/target/release/volta --version && \
        $PWD/target/release/volta setup --verbose
    runs-on: ubuntu-20.04
